baseURL = 'https://tecnopollo.github.io'
languageCode = 'es'
title = 'Tecnopollo'
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
privacy_pack = true
contentratio = 0.7

[params] 
title = "Tecnopollo"
description = "Informatica Informal"
profilePicture = "images/p.jpg"
Copyright = "Tecnopollo. Ningún derecho reservado"
#hidesidebar = true
contentratio = 0.8
